### ISSUE TITLE
epi-folder

### ISSUE THREAD

**Issue by lilysh** [aigoyal/EPItome-xl#21]
When running epi-folder the following error occurs:

Traceback (most recent call last):
  File "/srv/CODE/epitome/bin/epi-folder", line 176, in <module>
    main()
  File "/srv/CODE/epitome/bin/epi-folder", line 105, in main
    dir_data, dir_pipe, dir_afni, cores = epi.config.return_paths()
AttributeError: 'module' object has no attribute 'return_paths'

**Comment by josephdviviano** [comment]
Fixed in latest update.

**Comment by aigoyal** [comment]
@lilysh: pipeline is now up-to-date on cannlab server with the latest from Joseph's
